graph TD
    A[API Gateway] --> B[Auth Service]
    A --> C[Itinerary Service]
    A --> D[Payment Service]
    A --> E[Group Collaboration Service]
    A --> F[Notification Service]
    A --> G[User Profile Service]
    A --> L[Inventory Service]
    B --> H[(Auth DB)]
    C --> I[(Itinerary DB)]
    D --> J[(Payment DB)]
    E --> K[(Collab DB)]
    G --> M[(User DB)]
    L --> N[(Inventory Cache)]
